apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  clusterIP: {{ .Values.service.clusterIp }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.image.containerPort}}
      targetPort: {{ .Values.image.containerPort}}
